apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-cluster-multi-source-helm-chart
  namespace: kubechecks
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: podinfo
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: podinfo
    repoURL: https://stefanprodan.github.io/podinfo
    targetRevision: 6.7.0
    helm:
      valueFiles:
        - $values/apps/multi-source-helm-chart/values.yaml

  - repoURL: ${REPO_URL}
    targetRevision: HEAD
    ref: values

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

