apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubechecks
  namespace: {{ .Values.argocd.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
