{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubechecks.fullname" . }}
  annotations:
    {{ .Values.service.annotations | toYaml | nindent 4 }}
  labels:
    {{- include "kubechecks.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.name }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "kubechecks.selectorLabels" . | nindent 4 }}
{{- end }}
